### PR TITLE
[REPO SYNC] add support for CentOS8

### PR DESCRIPTION
**Pull request by cloudalchemybot**
One or more files which should be in sync across cloudalchemy repos were changed either here or in [cloudalchemy/skeleton](https://github.com/cloudalchemy/skeleton).
This PR propagates files from [cloudalchemy/skeleton](https://github.com/cloudalchemy/skeleton). If something was changed here, please first modify skeleton repository.

CC: @paulfantom.

### CODE REVIEW

**Comment by paulfantom** [comment]
@jkrol2 any ideas why apt cannot validate certs for `packages.treasuredata.com` on newer debian-based distros? Any ideas on how to fix this?

**Comment by jkrol2** [comment]
@paulfantom I'll take a look at this on weekend

**Comment by paulfantom** [comment]
@jkrol2 ping :)

**Comment by jkrol2** [comment]
@paulfantom very sorry. Things have gone a bit crazy recently and I've got little time to look at this. Since now I've found no cause of it

**Pull request merged**
